on:
  pull_request:
    types: [closed]

jobs:
  checkVersion:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read VERSION file
        id: getversion
        run: |
          mainVersion = $(cat product.version)
          branchVersion = $(git show $test:product.version)
          echo $mainVersion $branchVersion
