on:
  push:
  #pull_request:
    #types: [closed]

jobs:
  checkVersion:
    runs-on: ubuntu-latest
    outputs:
     mainVersion: ${{steps.getversionMain.outputs.mainVersion}}
     branchVersion: ${{steps.getversionMain.outputs.branchVersion}}
    #if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: getversionMain	
        run: |
          echo "::set-output name=mainversion::$(cat product.version)"
      - id: getversionBranch
        run: |
          echo "::set-output name=branchversion::$(git show $test:product.version)"
 
  CreateRelease:
    needs: checkVersion
    runs-on: ubuntu-latest
    if: ${{needs.checkVersion.outputs.mainVersion}} == ${{needs.checkVersion.outputs.branchVersion}} 
    #&& (github.event.pull_request.merged == true)
    steps:
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release: $(git show $test:releaseName)
        with:
          tag_name: ${{needs.checkVersion.outputs.mainVersion}}
          release_name: ${{needs.checkVersion.outputs.mainVersion}} 
          draft: true
          prerelease: false
      
