on:
  #push:
  pull_request:
    types: [closed]

jobs:
  checkVersion:
    runs-on: ubuntu-latest
    outputs:
      mainVersion: ${{steps.getversionMain.outputs.mainVersion}}
      branchVersion: ${{steps.getversionMain.outputs.branchVersion}}
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: getversionMain	
        run: |
          echo "::set-output name=mainversion::$(cat product.version)"
      - id: getversionBranch
        run: |
          echo "::set-output name=branchversion::$(git show $test:product.version)"
 
  CreateRelease:
    needs: checkVersion
    runs-on: ubuntu-latest
    if: ${{needs.checkVersion.outputs.mainVersion}} == ${{needs.checkVersion.outputs.branchVersion}} && (github.event.pull_request.merged == true)
    steps:
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release: $(git show $test:releaseName)
        with:
          tag_name: ${{needs.checkVersion.outputs.mainVersion}}
          release_name: ${{needs.checkVersion.outputs.mainVersion}} 
          draft: true
          prerelease: false
      - name: Create artifact files
        run: |
          mkdir info
          echo "${{ steps.create_release.outputs.id }}" > info/release_id
          echo "${{ steps.create_release.outputs.upload_url }}" > info/upload_url
      - uses: actions/upload-artifact@v1
        with:
          name: info
          path: info
          
      - name: Publish Release    
        uses: actions/download-artifact@v1
        with:
          name: info
      - name: Set publish_info
        id: publish_info
        run: |
          release_id=$(cat info/release_id)
          echo "::set-output name=release_id::$release_id"
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.publish_info.outputs.release_id }}  
