on:
  push:
  #pull_request:
    #types: [closed]

jobs:
  checkVersion:
    runs-on: ubuntu-latest
    #if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read VERSION file
        id: getversion
        run: |
          echo "$(cat product.version)" 
          echo "$(git show $test:product.version)" 
  CreateRelease:
    needs: checkVersion
    if: $(cat product.version) == $(git show $test:product.version) 
    #&& (github.event.pull_request.merged == true)
    steps:
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release: $(git show $test:releaseName)
        with:
          tag_name: $(cat product.version)
          release_name: $release 
          draft: true
          prerelease: false
      
