on:
  pull_request:
    types: [closed]

jobs:
  checkVersion:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read VERSION file
        id: getversion
      - run:
	  name: version check
	  command: |
            echo "$(cat product.version)" >> $mainVersion
            echo "$(git show $test:product.version)" >> $branchVersion
            echo $mainVersion $branchVersion
