on:
  pull_request:
    types: [closed]

jobs:
  checkVersion:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat product.version)"
